### ISSUE TITLE
Create Registration User Interface

### ISSUE THREAD

**Issue by seanpmyers** [seanpmyers/loremaster#20]
# Create Registration User Interface

## Context

Any person that wants to use the application must first register themselves with the application's database.
In order for them to do that, they need a user interface to interact with the application.

## Essentials

The user interface must be able to collect the following information from the user:

- The person's email address -- this is their primary form of identity
- A password -- this is a secret shared between the user and the application, used by the user to prove to the application they are who they claim to be.

## Optional

- An alias -- the user may wish to be greeted by the application using a certain alias. They don't have to provide this though.

## Tasks

- [ ] Design the interface
- [ ] Code the interface
- [ ] Test the interface

**Comment by seanpmyers** [comment]
#43
