### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by seanpmyers** [seanpmyers/loremaster#21]
# Update Documentation

## Context

Documentation helps those unfamiliar with the project/application become more familiar with it.
It can also be used to provide explanation for the reasoning behind certain decisions and implementations.
This can also keep the developers honest and improve their own understanding of why the project is the way it is.

## Tasks

- [ ] Record decisions and explanations for them
- [ ] Organize concepts and their records
- [ ] Record implementations and explanations for them
