### ISSUE TITLE
User Data Encryption

### ISSUE THREAD

**Issue by seanpmyers** [seanpmyers/loremaster#88]
# User Data Encryption

## Context

Currently the application architecture is that of a web application.   
The current architecture stores user data in a database running on servers not owned or managed by the users.  
This means that users are unable to ensure that their data is secure themselves and therefore they must rely on the host of the application and database.

While in the future there may be additional implementations of the application that allow the user to utilize it's features without relying on external parties, currently the application host holds responsibility for almost all security of the user's data.  

One way to protect user data is to use encryption to prevent anyone from reading it.  
Using a [key derivation function](https://en.wikipedia.org/wiki/Key_derivation_function) the encryption can be locked using the user's password as a key.  

Currently [argon2](https://en.wikipedia.org/wiki/Argon2) is being used to encrypt user passwords using 

## Tasks

- [ ] Determine what data should be encrypted
- [ ] Add functionality to encrypt user data
- [ ] Research best practices

## Resources

- [OWASP](https://owasp.org/Top10/A02_2021-Cryptographic_Failures/)
