### ISSUE TITLE
User Interface Design - Personal Page

### ISSUE THREAD

**Issue by seanpmyers** [seanpmyers/loremaster#89]
# User Interface Design- Personal Page

## Context

Since the application's functionality would benefit from more information about the user, it might make sense to have a page dedicated to meta-data about the user themselves.  

## Tasks

- [ ] Pick a name for the page
- [ ] Determine what information to collect from the user
- [ ] Determine what the interface should look like

## Page/View Name

Ideas:

- You
- Personal
- Me
- Self

## Data Collection

- User's alias/name
- Date of birth / age
- Email address
